version: '3.8'

networks:
  todo-net:
  
services:
  web-api:
    build: ./web
    command: python app.py
    ports:
      - target: 8080
        published: 5002
    expose:
      - "8080"
    networks:
      - todo-net
    
        
    
  
    
  